import { ArrowRight, ChartPie, CheckCircle2, Plane, Sparkles, Users, WalletCards } from 'lucide-react';
import { useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { ErrorBox } from '../components/ui';

export function Landing() {
  const { user } = useAuth(); if (user) return <Navigate to="/app" replace />;
  return <div className="min-h-screen bg-white"><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div className="flex items-center gap-2 text-xl font-extrabold text-travel"><span className="grid h-10 w-10 place-items-center rounded-xl bg-travel text-white"><Plane/></span>UsTrip</div><div className="flex gap-3"><Link className="btn-secondary" to="/login">Đăng nhập</Link><Link className="btn-primary" to="/register">Bắt đầu</Link></div></nav>
    <main className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-2 lg:items-center lg:py-28"><div><span className="badge bg-blue-50 text-travel"><Sparkles size={14} className="mr-1"/>Group travel, made clear</span><h1 className="mt-6 text-5xl font-extrabold leading-tight tracking-tight md:text-6xl">Đi cùng nhau.<br/><span className="text-travel">Rõ từng khoản.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Lên lịch trình, quản lý quỹ chung, chia chi phí và nhắc thanh toán trong một nơi duy nhất.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="btn-coral">Tạo chuyến đi đầu tiên <ArrowRight size={18}/></Link><Link to="/login" className="btn-secondary">Xem tài khoản mẫu</Link></div></div>
      <div className="relative rounded-[32px] bg-gradient-to-br from-blue-600 to-travel p-6 shadow-lift"><div className="rounded-2xl bg-white p-5"><div className="mb-5 flex justify-between"><div><p className="text-xs font-bold uppercase text-slate-400">Chuyến đi sắp tới</p><h3 className="mt-1 text-xl font-bold">Phượt Đà Lạt</h3></div><span className="badge bg-emerald-50 text-emerald-700">Đang chuẩn bị</span></div><div className="grid grid-cols-2 gap-3">{[[WalletCards,'Quỹ chung','6.000.000đ'],[ChartPie,'Đã chi','360.000đ'],[Users,'Thành viên','3 người'],[CheckCircle2,'Hoạt động','2 mục']].map(([Icon,l,v])=><div className="rounded-xl bg-slate-50 p-4" key={l}><Icon className="mb-3 text-travel"/><p className="text-xs text-slate-500">{l}</p><p className="mt-1 font-bold">{v}</p></div>)}</div></div></div></main></div>;
}

export function AuthPage({ mode }) {
  const isRegister = mode === 'register'; const { user, login, register } = useAuth(); const navigate = useNavigate();
  const [form, setForm] = useState({ full_name: '', email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  if (user) return <Navigate to="/app" replace />;
  const submit = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { await (isRegister ? register(form) : login(form)); navigate('/app'); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <div className="grid min-h-screen bg-white lg:grid-cols-2"><div className="hidden bg-gradient-to-br from-blue-700 to-travel p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-2 text-2xl font-extrabold"><Plane/>UsTrip</div><div><h2 className="text-5xl font-extrabold leading-tight">Mỗi chuyến đi<br/>là một câu chuyện chung.</h2><p className="mt-5 max-w-md text-blue-100">Minh bạch chi phí để cả nhóm chỉ cần tập trung vào trải nghiệm.</p></div><p className="text-sm text-blue-200">UsTrip · Group Travel Hub</p></div><div className="flex items-center justify-center p-5"><form onSubmit={submit} className="w-full max-w-md"><Link to="/" className="mb-10 flex items-center gap-2 text-xl font-extrabold text-travel lg:hidden"><Plane/>UsTrip</Link><h1 className="text-3xl font-extrabold">{isRegister ? 'Tạo tài khoản' : 'Chào mừng trở lại'}</h1><p className="mb-8 mt-2 text-slate-500">{isRegister ? 'Bắt đầu tổ chức chuyến đi của bạn.' : 'Đăng nhập để tiếp tục hành trình.'}</p><ErrorBox message={error}/>{isRegister && <div className="mb-4"><label>Họ và tên</label><input required value={form.full_name} onChange={(e)=>setForm({...form,full_name:e.target.value})}/></div>}<div className="mb-4"><label>Email</label><input required type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})}/></div><div className="mb-6"><label>Mật khẩu</label><input required minLength={8} type="password" value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})}/></div><button disabled={busy} className="btn-primary w-full">{busy ? 'Đang xử lý...' : isRegister ? 'Đăng ký' : 'Đăng nhập'}</button><p className="mt-6 text-center text-sm text-slate-500">{isRegister ? 'Đã có tài khoản?' : 'Chưa có tài khoản?'} <Link className="font-bold text-travel" to={isRegister ? '/login' : '/register'}>{isRegister ? 'Đăng nhập' : 'Đăng ký'}</Link></p></form></div></div>;
}
